# -*- coding: utf-8 -*-
"""modul penjumlahan.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JtGyNJsamKulR5g3v3lk8tJmlnkKztV8
"""

def penjumlahan(angka1, angka2):
  angka1 = 5
  angka2 = 3
  jumlah = angka1 + angka2
  return jumlah